apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  # ì‚¬ìš©í•  ì¸ê·¸ë ˆìŠ¤ ì»¨íŠ¸ë¡¤ëŸ¬ë¥¼ ì§€ì •í•˜ê³ , rewrite ê·œì¹™ì„ ì‚¬ìš©í•˜ê¸° ìœ„í•œ ì–´ë…¸í…Œì´ì…˜
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "zerossl-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/x-forwarded-proto: "https"
    nginx.ingress.kubernetes.io/limit-rps: "10" # ì´ˆë‹¹ 10ê°œ ìš”ì²­ìœ¼ë¡œ ì œí•œ
    nginx.ingress.kubernetes.io/limit-rpm: "600" # ë¶„ë‹¹ 600ê°œ ìš”ì²­ìœ¼ë¡œ ì œí•œ
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
      - hosts:
          # ì¸ì¦ì„œë¥¼ ë°œê¸‰ë°›ì„ ë„ë©”ì¸ ì´ë¦„
          - jjangyushop.kro.kr # ğŸ‘ˆ ë³¸ì¸ì˜ ë„ë©”ì¸ìœ¼ë¡œ ë³€ê²½
        # ì¸ì¦ì„œê°€ ì €ì¥ë  Secretì˜ ì´ë¦„ (cert-managerê°€ ìë™ìœ¼ë¡œ ìƒì„±í•´ ì¤Œ)
        secretName: myapp-com-tls 
  rules:
  - host: jjangyushop.kro.kr
    http:
      paths:
        - path: /api(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              # ì´ì „ì— ë§Œë“  ë°±ì—”ë“œ ì„œë¹„ìŠ¤ì˜ ì´ë¦„ì„ ì •í™•íˆ ê¸°ì…í•©ë‹ˆë‹¤.
              name: backend-svc
              port:
                number: 80
        - path: /swagger-ui
          pathType: Prefix
          backend:
            service:
              # ì´ì „ì— ë§Œë“  ë°±ì—”ë“œ ì„œë¹„ìŠ¤ì˜ ì´ë¦„ì„ ì •í™•íˆ ê¸°ì…í•©ë‹ˆë‹¤.
              name: backend-svc
              port:
                number: 80
        # ê·¸ ì™¸ì˜ ëª¨ë“  ê²½ë¡œëŠ” í”„ë¡ íŠ¸ì—”ë“œ ì„œë¹„ìŠ¤ë¡œ ì—°ê²°í•©ë‹ˆë‹¤.
        - path: /()(.*)
          pathType: Prefix
          backend:
            service:
              # ì´ì „ì— ë§Œë“  í”„ë¡ íŠ¸ì—”ë“œ ì„œë¹„ìŠ¤ì˜ ì´ë¦„ì„ ì •í™•íˆ ê¸°ì…í•©ë‹ˆë‹¤.
              name: frontend-svc
              port:
                number: 80
