apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  # ğŸ‘‡ í•µì‹¬: 'cluster-infra' ì‘ì—…ì´ ì„±ê³µì ìœ¼ë¡œ ëë‚˜ê¸° ì „ì—ëŠ” ì‹œì‘í•˜ì§€ ì•ŠìŒ
  dependsOn:
    - name: cluster-infra
  interval: 10m0s
  path: ./clusters/my-cluster/apps # 'apps' í´ë”ë¥¼ ê°€ë¦¬í‚´
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system